language: python
python:
  # - "2.5"
  - "2.6"
  - "2.7"
  - "3.3"
  - "pypy"
install:
  - pip install coveralls
  - python setup.py install
script:
  - coverage run --source=stringscore setup.py test
  - coverage run -a -m stringscore.liquidmetal
  - coverage run -a -m stringscore.quicksilver
  - coverage report
after_script:
  coveralls --verbose
