language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"
install:
  - pip install coveralls
  - python setup.py install
script:
  - make coverage
after_script:
  coveralls --verbose
